### ISSUE TITLE
Consider use of functions as well?

### ISSUE THREAD

**Issue by KantarBruceAdams** [Parquery/gocontracts#22]
Hi,
    I have been looking for DBC support for go as well. I like your approach of ensuring that the generated code agrees with the documentation. I wonder if we could have the best of both worlds if you generated code that used functions to implement the contract as per https://godoc.org/github.com/lpabon/godbc?

Personally I want to assert pre-conditions in production but not post-conditions (which are often hard to compute and covered by extensive unit tests.
I also want to document all my pre-conditions , post-condiions and invariants even those that are hard to compute.
Coming from C++ I used doxygen for DBC commenting, an assertion macro for pre-conditions and unit tests for post-conditions and invariants. Generating a contract checking wrapper to a function would be very useful in the testing context.

The ultimate DBC package to me, might allow:
 * just checking that pre-conditions, post-conditions and invariants in the code and documentation match
 * generating checks from documentation   - as you do now
 * generating documentation from checks - the inverse - which I presume is not done
 * allowing documented checks which are not generated
   e.g.  "foobar() must have been invoked first to setup the snafu"

I would like to propose a minimum change towards this goal of:
* allowing documented checks which are not generated
* using functions for the generated checks (like https://godoc.org/github.com/lpabon/godbc)
 so that your package is still usable/preferable even if the code generation part is not used.

I presume this package overwrites generated contracts rather than "checking that pre-conditions, post-conditions and invariants in the code and documentation match" which is a harder problem but please correct me if I am wrong.

What is the current behaviour if code for a check cannot be generated?
Is this left to be picked up as a build failure downstream?

Regards,

Bruce.

**Comment by KantarBruceAdams** [comment]
On a related note you depend on the godoc syntax specification but I cannot find one - https://stackoverflow.com/questions/53101458/where-is-the-specification-for-godoc-itslef

**Comment by mristin** [comment]
Hi @KantarBruceAdams 
I added a subsection to the Readme that should explain in a bit more detail how to toggle the contracts: https://github.com/Parquery/gocontracts#toggling-contracts

Please let me know if the text is clear enough.

**Comment by KantarBruceAdams** [comment]
Actually the main point of this:
* I wonder if we could have the best of both worlds if you generated code that used functions to implement the contract as per https://godoc.org/github.com/lpabon/godbc?
For example. For "len(args) >= 1" Instead of generating:

	// Pre-condition
	if !(len(args) >= 1) {
		panic("Violated: len(args) >= 1")
	}

You could generate:

	// pre-conditions
	godbc.Require(len(args) >= 1, "Violated: len(args) >= 1")

But I subverted my own thread.
Here I am using github.com/lpabon/godbc but you could provide something yourself or make it hookable.
The advantage of this would be.
1. you can use your library instead of godbc to hand write contract enforcement code
2. code implementing contracts is obvious even without the comment blocks (and potentially machine modifiable)

At the moment it is hard to mix gocontracts with godbc.

**Comment by mristin** [comment]
Hi @KantarBruceAdam,
Could you please clarify a bit the benefit of having a separate function?

I see it actually beneficial to dispense of a function call: the contract checking code is explicit and directly readable, while the constants in the conditions allow you to easily track in which situations the contract is verified (or not).

**Comment by mristin** [comment]
Hi @KantarBruceAdams ,
We implemented all these features (conditions as decorators and informative violation messages generated from the condition code) in our Python contract library (https://github.com/Parquery/icontract/). 

However, Go does not support such an approach: there are no macros and you don't even have optional arguments. That's why we implemented gocontracts in the first place: so that you define conditions only once, and you read them in the violation message automatically.

The only benefit of the function would be to assume that the user of the gocontracts can specify individually her `dbc` module and then choose from different functions. But this is such a marginal benefit to me (and rather confusing to folks who read the code) that I decided against it.

**Comment by KantarBruceAdams** [comment]
I have left an [honourable mention of gocontracts](https://github.com/golang/go/issues/23637) in regards to discussions about attributes/annotations in go. C++20 includes [contracts as attributes](https://en.cppreference.com/w/cpp/language/attributes/contract)

**Comment by mristin** [comment]
Thanks! I'll keep an eye on it. It would be so much better if they integrated DbC in the language.

**Comment by mristin** [comment]
Hi @KantarBruceAdams,
I've just added the support for contract preamble, so that you can use whatever library you want to assert the contracts (including `godbc`). For example:

```go
import "github.com/lpabon/godbc"

// SomeFunc does something.
//
// SomeFunc preamble:
//	godbc.Require(x > 0, "x positive")
//	godbc.Require(x < 100, "x not too large")
func SomeFunc(x int) {
	// Preamble
	godbc.Require(x > 0, "x positive")
	godbc.Require(x < 100, "x not too large")

	// function body ...
}
```

Could you please let me know if this resolves your issue?
