### ISSUE TITLE
Allow checks to be documented which are unenforced.

### ISSUE THREAD

**Issue by KantarBruceAdams** [Parquery/gocontracts#29]
For example:

```
// SomeFunc requires:
// * "some other func called first"
```

**Comment by mristin** [comment]
Could you please clarify? You can always make a condition as a constant `true` and include a description. Is that what you had in mind?

**Comment by mristin** [comment]
I thought about adding a clarification to the readme, but actually decided against it since we forbid unverified contracts in our code base at Parquery due to potential bugs related to documentation rot.
