### ISSUE TITLE
Use go doc safe comment style 

### ISSUE THREAD

**Issue by KantarBruceAdams** [Parquery/gocontracts#30]
I've been wrestling with godoc (I think I may drop it altogether as its far too simplistic).
Anyway I note that:

```
// SomeFunc does something.
//
// SomeFunc requires:
//  * x >= 0
//  * x < 100
//
// SomeFunc ensures:
//  * !strings.HasSuffix(result, "smth")
//
```

Renders as:

```
>go doc somePackage.SomeFunc
func SomeFunc(x int) (result string)
     SomeFunc does something.
 
     SomeFunc requires:
 
     * x >= 0
     * x < 100
 
     SomeFunc ensures:
 
     * !strings.HasSuffix(result, "smth")
``` 

which is nicer than the:
```

func SomeFunc(x int) (result string)
    SomeFunc does something.

    SomeFunc requires: * x >= 0 * x < 100

    SomeFunc ensures: * !strings.HasSuffix(result, "smth")

```
which you get without indenting the conditions and making them into a pre-formatted text block.
This doesn't affect gocontracts code generation at all.
Its purely a documentation issue to recommend users do this.

**Comment by mristin** [comment]
Thanks for spotting this! I'll update the doc.

**Comment by mristin** [comment]
Hi @KantarBruceAdams 
I updated the readme. Please re-open the issue if you think the readme is not clear enough.
